pipeline {
  agent {
    docker {
      image '10.166.0.10:5000/docker-agent:latest'
            args '-u root:sudo --privileged -v /var/run/docker.sock:/var/run/docker.sock'
            }
         }
  stages {

    stage('Copy source') {
      steps {
        git 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      }
    }

    stage('Build war') {
      steps {
        sh 'mvn package'
      }
    }

    stage('Preparations and Make docker image') {
      steps {
        sh 'ssh-keyscan -H 10.166.0.10 >> ~/.ssh/known_hosts'
        sh 'scp root@10.166.0.10:/root/prod/Dockerfile /root/docker/Dockerfile'
        sh 'cp ./target/hello-1.0.war /root/docker/hello-1.0.war && cd /root/docker/ && docker build --tag=prodserv .'
        sh 'docker tag prodserv 10.166.0.10:5000/prodserv && docker push 10.166.0.10:5000/prodserv'
      }
    }

    stage('Run docker prodserver') {
      steps {
        sh 'docker pull 10.166.0.10:5000/prodserv && docker run -d -p 80:80 prodserv '
      }
    }
  }
}

