---
- name: Set TimeZone Moscow for all hosts
  hosts: all
  roles:
    - yatesr.timezone
    - default
  vars:
    timezone: Europe/Moscow

- name: development configuration
  hosts: dev
  become: yes
  roles:
    - dev
#    - gantsign.maven

- name: production configuration
  hosts: prod
  become: yes
  roles:
    - prod

