FROM ubuntu:20.04
#USER root
ENV CATALINA_BASE /var/lib/tomcat9
ENV CATALINA_HOME /usr/share/tomcat9
ENV PATH $CATALINA_HOME/bin:$PATH
WORKDIR $CATALINA_HOME
ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt update &&  apt install default-jdk tomcat9 -y

EXPOSE 8080

ENTRYPOINT ["catalina.sh", "run"]
